#source common.sh # Importing functions and variables from commmon.sh file
#component=frontend
#Head "Installing Nginx"
#dnf install nginx -y &>>$log_file
#Stat $?
#
#Head "Copying expense config"
#cp expense.conf /etc/nginx/default.d/expense.conf &>>$log_file
#Stat $?
#
#App_Prereq "/usr/share/nginx/html" # Added this function in common.sh with steps that are repeating in other
#  #Files also and using it here
#
#Head "Enabling and restarting nginx"
#systemctl enable nginx &>>$log_file
#systemctl restart nginx &>>$log_file
#Stat $?

- name: Setup of Frontend
  become: true  # This is same to -b in command line we used for getting sudo access
  hosts: all
  tasks:
    - name: Installing Nginx
      ansible.builtin.dnf:  # We are using this dnf as we are using python3 if python2 use yum
        name: nginx
        state: installed
    - name: Copying expense Configuration File #reverse proxy server
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf
    - name: Deleting the existing App Content
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent
    - name: Creating a App Directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory
    - name: Downloading the App content
      ansible.builtin.get_url:
        url: https://expense-artifacts.s3.amazonaws.com/frontend.zip
        dest: /tmp/frontend.zip
    - name: Extracting Application Content
      ansible.builtin.unarchive:
        src: /tmp/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes