#MYSQL_PASSWORD=$1
#if [ -z "$MYSQL_PASSWORD" ]; then
#echo "Input MySql Password is missing"
#exit 1
#fi
#source common.sh # Importing functions and variables from common.sh file
#component=my_sql
#
#Head "Disable default version of mysql"
#dnf module disable mysql -y &>>$log_file
#Stat $?
#
#Head "Setting mysql repo file"
#cp mysql.repo /etc/yum.repos.d/mysql.repo &>>$log_file
#Stat $?
#
#Head "Installing Mysql Server"
#dnf install mysql-community-server -y &>>$log_file
#Stat $?
#
#Head "Restarting mysqld service"
#systemctl enable mysqld &>>$log_file
#systemctl start mysqld &>>$log_file
#Stat $?
#
#Head "Setting default password"
#mysql_secure_installation --set-root-pass ${MYSQL_PASSWORD=$1} &>>$log_file
#Stat $?

- name: MySQL Setup
  hosts: all
  become: true
  tasks:
    - name: Disable default version of mysql
      ansible.builtin.shell: dnf module disable mysql -y  # dnf module is not supporting as of now so we are using shell module

    - name: Copy mysql repo file
      ansible.builtin.copy:
       src: mysql.repo
       dest: /etc/yum.repos.d/mysql.repo

    - name: Installing Mysql Server
      ansible.builtin.dnf:
        name: mysql-community-server
        state: installed
    - name: Restarting mysqld service
      ansible.builtin.systemd_service:
        name: mysqld
        state: restarted
    - name: Setting default password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1
