- name: Disable default version of mysql
  ansible.builtin.shell: dnf module disable mysql -y  # dnf module is not supporting as of now so we are using shell module

- name: Copy mysql repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Installing Mysql Server
  ansible.builtin.dnf:
    name: mysql-community-server
    state: installed
- name: Restarting mysqld service
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
- name: Setting default password
  #ansible.builtin.shell: type mysql_secure_installation
  register: out
  ansible.builtin.shell: bash -x /usr/sbin/mysql_secure_installation --set-root-pass msg="{{ lookup('amazon.aws.aws_ssm', 'dev.mysql.root_password', region='us-east-1' ) }}"
- name: out
  debug:
    msg: "{{ out }}"